# Generated by Django 5.1.6 on 2025-04-16 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=100, unique=True)),
                ('case_number', models.CharField(blank=True, max_length=255, null=True)),
                ('neutral_citation', models.CharField(blank=True, max_length=255, null=True)),
                ('court', models.TextField(blank=True, null=True)),
                ('judges', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('hearing_date', models.CharField(blank=True, max_length=100, null=True)),
                ('parties', models.JSONField(blank=True, null=True)),
                ('representatives', models.JSONField(blank=True, null=True)),
                ('case_text', models.TextField(blank=True)),
            ],
        ),
    ]
