# Generated by Django 5.1.6 on 2025-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('case_number', models.TextField(blank=True, null=True)),
                ('neutral_citation', models.TextField(blank=True, null=True)),
                ('court', models.TextField(blank=True, null=True)),
                ('hearing_date', models.TextField(blank=True, null=True)),
                ('judges', models.JSONField(blank=True, null=True)),
                ('parties', models.JSONField(blank=True, null=True)),
                ('representatives', models.JSONField(blank=True, null=True)),
                ('text_path', models.TextField()),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
