# Generated by Django 5.1.6 on 2025-04-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casemetadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='casemetadata',
            name='file_name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
