# Generated by Django 5.1.6 on 2025-04-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_casemetadata_id_alter_casemetadata_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemetadata',
            name='semantic_text_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
